# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predicate',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='predicate',
            name='rank',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predicate',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predicate',
            name='total_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='_consensus_decision_threshold',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='_consensus_uncertainty_threshold',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='avg_completion_time',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='avg_tasks_per_pair',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='cost',
            field=models.FloatField(default=1.0),
        ),
    ]
