# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0002_auto_20181010_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_pair',
            name='end_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='pairs_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='queue_length',
            field=models.IntegerField(default=2000),
        ),
    ]
