# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0002_auto_20190530_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predicate',
            name='question',
        ),
        migrations.AddField(
            model_name='ip_pair',
            name='correct_matches',
            field=models.CharField(default=b'', max_length=300),
        ),
        migrations.AddField(
            model_name='ip_pair',
            name='end_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ip_pair',
            name='join_fins',
            field=models.CharField(default=b'[false, false, false, false, false, false]', max_length=60),
        ),
        migrations.AddField(
            model_name='ip_pair',
            name='join_pairs',
            field=models.CharField(default=b'', max_length=400),
        ),
        migrations.AddField(
            model_name='ip_pair',
            name='small_p_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ip_pair',
            name='task_types',
            field=models.CharField(default=b'', max_length=400),
        ),
        migrations.AddField(
            model_name='item',
            name='pairs_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predicate',
            name='correct_matches',
            field=models.CharField(default=b'', max_length=1000),
        ),
        migrations.AddField(
            model_name='predicate',
            name='joinable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predicate',
            name='question_str',
            field=models.CharField(default=b'', max_length=400),
        ),
        migrations.AddField(
            model_name='predicate',
            name='task_types',
            field=models.CharField(default=b'', max_length=400),
        ),
        migrations.AddField(
            model_name='predicate',
            name='tasks_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predicate',
            name='times_taken',
            field=models.CharField(default=b'', max_length=9000),
        ),
        migrations.AddField(
            model_name='task',
            name='predicate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamicfilterapp.Predicate'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(default=b'default', max_length=15),
        ),
        migrations.AddField(
            model_name='task',
            name='type_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='predicate_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='queue_length',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='task',
            name='ip_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamicfilterapp.IP_Pair'),
        ),
    ]
