from django import forms
from models import Restaurant, RestaurantPredicate

class WorkerForm(forms.Form):
    answer = forms.NullBooleanField(label='Your answer')

class RestaurantAdminForm(forms.ModelForm):

	class Meta:
		# Tells Django which model this form is creating and which fields to display
		model = Restaurant
		fields = ['name', 'url', 'text', 'street', 'city',
				'state', 'zipCode', 'country']

	def save(self, commit=True):
		# Save (create or update) the Restaurant generated by this form
		instance = super(RestaurantAdminForm, self).save(commit=False)
		instance.save()
		# Create the three associated predicates if they don't exist  yet
		RestaurantPredicate.objects.get_or_create(restaurant=instance, question="Does this restaurant accept credit cards?")
		RestaurantPredicate.objects.get_or_create(restaurant=instance, question="Is this a good restaurant for kids?")
		RestaurantPredicate.objects.get_or_create(restaurant=instance, question="Does this restaurant serve Choco Pies?")
		return instance

class IDForm(forms.Form):
	workerID = forms.IntegerField(label='Worker ID', min_value=0)
