# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Primary_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_ID', models.IntegerField(default=None)),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=50)),
                ('eval_result', models.BooleanField(db_index=True, default=False)),
                ('is_done', models.BooleanField(db_index=True, default=False)),
                ('num_sec_items', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PS_Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consensus', models.BooleanField(db_index=True, default=None)),
                ('yes_votes', models.IntegerField(default=0)),
                ('no_votes', models.IntegerField(default=0)),
                ('ambiguity', models.CharField(default='No Consensus', max_length=50)),
                ('prim_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinapp.Primary_Item')),
            ],
        ),
        migrations.CreateModel(
            name='Secondary_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_ID', models.IntegerField(default=None)),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=50)),
                ('second_pred_consensus', models.BooleanField(db_index=True, default=None)),
                ('yes_votes', models.IntegerField(default=0)),
                ('no_votes', models.IntegerField(default=0)),
                ('ambiguity', models.CharField(default='No Consensus', max_length=50)),
                ('num_prim_items', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ps_pair',
            name='sec_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinapp.Secondary_Item'),
        ),
        migrations.AddField(
            model_name='primary_item',
            name='secondary_items',
            field=models.ManyToManyField(related_name='primary_items', to='joinapp.Secondary_Item'),
        ),
    ]
