# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0002_auto_20190605_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondary_item',
            name='second_pred_consensus',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
    ]
