# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-14 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0005_auto_20190614_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPJFPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pjf', models.CharField(max_length=10)),
                ('consensus', models.BooleanField(db_index=True, default=False)),
                ('yes_votes', models.IntegerField(default=0)),
                ('no_votes', models.IntegerField(default=0)),
                ('pjf_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinapp.PJFTask')),
            ],
        ),
        migrations.AddField(
            model_name='primaryitem',
            name='pjf',
            field=models.CharField(default='false', max_length=10),
        ),
        migrations.AddField(
            model_name='secondaryitem',
            name='pjf',
            field=models.CharField(default='false', max_length=10),
        ),
        migrations.AddField(
            model_name='itempjfpair',
            name='primary_item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='joinapp.PrimaryItem'),
        ),
        migrations.AddField(
            model_name='itempjfpair',
            name='secondary_item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='joinapp.SecondaryItem'),
        ),
    ]
