# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0006_auto_20190614_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinpairtask',
            name='find_pairs_task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='joinapp.FindPairsTask'),
        ),
    ]
