# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0007_auto_20190617_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempjfpair',
            name='consensus',
        ),
        migrations.AddField(
            model_name='itempjfpair',
            name='result',
            field=models.NullBooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='findpairstask',
            name='consensus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='joinpairtask',
            name='find_pairs_task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='joinapp.FindPairsTask'),
        ),
        migrations.AlterField(
            model_name='pjftask',
            name='consensus',
            field=models.BooleanField(default=False),
        ),
    ]
