# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0008_auto_20190619_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='findpairstask',
            old_name='time',
            new_name='average_time',
        ),
        migrations.RenameField(
            model_name='jftask',
            old_name='time',
            new_name='average_time',
        ),
        migrations.RenameField(
            model_name='joinpairtask',
            old_name='time',
            new_name='average_time',
        ),
        migrations.RenameField(
            model_name='pjftask',
            old_name='time',
            new_name='average_time',
        ),
        migrations.RenameField(
            model_name='secpredtask',
            old_name='time',
            new_name='average_time',
        ),
        migrations.AddField(
            model_name='findpairstask',
            name='total_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jftask',
            name='total_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='joinpairtask',
            name='total_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pjftask',
            name='total_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='secpredtask',
            name='total_time',
            field=models.FloatField(default=0),
        ),
    ]
