# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0008_auto_20190619_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempjfpair',
            name='consensus',
        ),
        migrations.AddField(
            model_name='itempjfpair',
            name='result',
            field=models.NullBooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='primaryitem',
            name='has_all_join_pairs',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='secondaryitem',
            name='num_prims_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='findpairstask',
            name='consensus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pjftask',
            name='consensus',
            field=models.BooleanField(default=False),
        ),
    ]
