# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0009_auto_20190620_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryitem',
            name='has_all_join_pairs',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
