# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-26 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0009_auto_20190621_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='findpairstask',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itempjfpair',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jftask',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='joinpairtask',
            name='has_same_pjf',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='joinpairtask',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pjftask',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='secpredtask',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
