# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0011_secondaryitem_num_prims_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondaryitem',
            name='num_prims_left',
        ),
    ]
