# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0013_secondaryitem_num_prims_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinpairtask',
            name='has_same_pjf',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
