# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0028_ip_pair_pastworkers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completionTime',
        ),
        migrations.AddField(
            model_name='ip_pair',
            name='status_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ip_pair',
            name='num_votes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ip_pair',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='num_pending',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='num_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
