# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0031_remove_task_completiontime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip_pair',
            name='status_votes',
        ),
    ]
