# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0033_ip_pair_status_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='predicate',
            name='queue_is_Full',
            field=models.BooleanField(default=False),
        ),
    ]
