# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0035_auto_20160617_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip_pair',
            name='pastWorkers',
        ),
    ]
