# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0044_ip_pair_inqueue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='almostFalse',
            new_name='almostDone',
        ),
    ]
