# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0045_auto_20160705_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inQueue',
            field=models.BooleanField(default=False),
        ),
    ]
