# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0047_auto_20160707_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='predicate',
            name='num_ip_complete',
            field=models.IntegerField(default=0),
        ),
    ]
