# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0048_predicate_num_ip_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='predicate',
            name='num_escrow',
            field=models.IntegerField(default=1),
        ),
    ]
