# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0049_predicate_num_escrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip_pair',
            name='isDone',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
