# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0050_auto_20160715_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='workerID',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
