# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0051_auto_20160715_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hasFailed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
