# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0056_delete_ticketlifetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
