# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0058_auto_20160722_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='almostDone',
            new_name='almostFalse',
        ),
        migrations.RenameField(
            model_name='predicate',
            old_name='num_escrow',
            new_name='num_wickets',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
