# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0060_auto_20160727_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='queueIndex',
        ),
    ]
