# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0061_remove_item_queueindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_pair',
            name='isStarted',
            field=models.BooleanField(default=False),
        ),
    ]
