# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0062_ip_pair_isstarted'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shouldPass',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
