# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0062_ip_pair_isstarted'),
    ]

    operations = [
        migrations.AddField(
            model_name='predicate',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predicate',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
