# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import dynamicfilterapp.validator


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0063_auto_20170615_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip_pair',
            name='inQueue',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='workerid',
            name='workerID',
            field=models.IntegerField(db_index=True, unique=True, validators=[dynamicfilterapp.validator.validate_positive]),
        ),
    ]
