# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0063_item_shouldpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='endTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='startTime',
            field=models.IntegerField(default=0),
        ),
    ]
