# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0064_auto_20170615_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_pair',
            name='tasks_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predicate',
            name='queue_length',
            field=models.IntegerField(default=10),
        ),
    ]
