# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0064_auto_20170623_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='predicate',
            name='rank',
            field=models.FloatField(default=0.0),
        ),
    ]
