# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0066_auto_20170623_1137'),
        ('dynamicfilterapp', '0065_predicate_rank'),
    ]

    operations = [
    ]
