# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0026_auto_20150804_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP_Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('num_votes', models.IntegerField(default=0)),
                ('isDone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_ID', models.IntegerField(default=None)),
                ('name', models.CharField(max_length=50)),
                ('item_type', models.CharField(max_length=50)),
                ('hasFailed', models.BooleanField(default=False)),
                ('queueIndex', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Predicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate_ID', models.IntegerField(default=None)),
                ('num_tickets', models.IntegerField(default=None)),
                ('num_pending', models.IntegerField(default=None)),
                ('selectivity', models.FloatField(default=0.1)),
                ('totalTasks', models.FloatField(default=0.0)),
                ('totalNo', models.FloatField(default=0.0)),
                ('cost', models.FloatField(default=None)),
                ('avg_completion_time', models.FloatField(default=0.0)),
                ('avg_tasks_per_pair', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ID', models.IntegerField(default=None)),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='PredicateBranch',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurantpredicate',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='task',
            name='IDontKnow',
        ),
        migrations.RemoveField(
            model_name='task',
            name='confidenceLevel',
        ),
        migrations.RemoveField(
            model_name='task',
            name='restaurantPredicate',
        ),
        migrations.AlterField(
            model_name='task',
            name='completionTime',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='task',
            name='workerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamicfilterapp.WorkerID'),
        ),
        migrations.DeleteModel(
            name='RestaurantPredicate',
        ),
        migrations.AddField(
            model_name='predicate',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamicfilterapp.Question'),
        ),
        migrations.AddField(
            model_name='ip_pair',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamicfilterapp.Item'),
        ),
        migrations.AddField(
            model_name='ip_pair',
            name='predicate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamicfilterapp.Predicate'),
        ),
        migrations.AddField(
            model_name='task',
            name='ip_pair',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dynamicfilterapp.IP_Pair'),
        ),
    ]
