# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0032_remove_ip_pair_status_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_pair',
            name='status_votes',
            field=models.IntegerField(default=0),
        ),
    ]
