# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0034_predicate_queue_is_full'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predicate',
            old_name='queue_is_Full',
            new_name='queue_is_full',
        ),
    ]
