# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0040_auto_20160621_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isStarted',
            field=models.BooleanField(default=False),
        ),
    ]
