# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0041_item_isstarted'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='almostFinished',
            field=models.BooleanField(default=False),
        ),
    ]
