# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0042_item_almostfinished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='almostFinished',
            new_name='almostFalse',
        ),
    ]
