# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0043_auto_20160628_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_pair',
            name='inQueue',
            field=models.BooleanField(default=False),
        ),
    ]
