# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0046_item_inqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicate',
            name='num_tickets',
            field=models.IntegerField(default=1),
        ),
    ]
