# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfilterapp', '0052_auto_20160715_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketLifetime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifetime', models.IntegerField(default=50)),
            ],
        ),
    ]
