# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primary_item',
            old_name='item_ID',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='secondary_item',
            old_name='item_ID',
            new_name='item_id',
        ),
        migrations.AlterField(
            model_name='ps_pair',
            name='consensus',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
    ]
