# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0003_auto_20190605_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primary_item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='secondary_item',
            name='id',
        ),
        migrations.AlterField(
            model_name='primary_item',
            name='item_id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='secondary_item',
            name='item_id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
