# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0005_auto_20190606_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Primary_Item',
            new_name='PrimaryItem',
        ),
        migrations.RenameModel(
            old_name='Secondary_Item',
            new_name='SecondaryItem',
        ),
    ]
