# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0006_auto_20190606_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindPairsTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consensus', models.NullBooleanField(default=None)),
                ('primary_item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='joinapp.PrimaryItem')),
            ],
        ),
        migrations.CreateModel(
            name='JFTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_votes', models.IntegerField(default=0)),
                ('no_votes', models.IntegerField(default=0)),
                ('consensus', models.NullBooleanField(default=None)),
                ('ambiguity', models.CharField(max_length=16)),
                ('primary_item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='joinapp.PrimaryItem')),
            ],
        ),
        migrations.CreateModel(
            name='JoinPairTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_votes', models.IntegerField(default=0)),
                ('no_votes', models.IntegerField(default=0)),
                ('consensus', models.NullBooleanField(default=None)),
                ('ambiguity', models.CharField(max_length=16)),
                ('primary_item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='joinapp.PrimaryItem')),
                ('secondary_item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='joinapp.SecondaryItem')),
            ],
        ),
        migrations.CreateModel(
            name='PJFTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consensus', models.NullBooleanField(default=None)),
                ('primary_item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='joinapp.PrimaryItem')),
                ('secondary_item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='joinapp.SecondaryItem')),
            ],
        ),
        migrations.CreateModel(
            name='SecPredTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_votes', models.IntegerField(default=0)),
                ('no_votes', models.IntegerField(default=0)),
                ('consensus', models.NullBooleanField(default=None)),
                ('ambiguity', models.CharField(max_length=16)),
                ('secondary_item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='joinapp.SecondaryItem')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('ambiguity', models.FloatField(default=0)),
                ('selectivity', models.FloatField()),
                ('avg_num_pairs', models.IntegerField(default=0)),
                ('num_processed', models.IntegerField(default=0)),
            ],
        ),
    ]
