# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0007_findpairstask_jftask_joinpairtask_pjftask_secpredtask_taskstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jftask',
            old_name='consensus',
            new_name='result',
        ),
        migrations.RenameField(
            model_name='joinpairtask',
            old_name='consensus',
            new_name='result',
        ),
        migrations.RenameField(
            model_name='secpredtask',
            old_name='consensus',
            new_name='result',
        ),
        migrations.RemoveField(
            model_name='jftask',
            name='ambiguity',
        ),
        migrations.RemoveField(
            model_name='joinpairtask',
            name='ambiguity',
        ),
        migrations.RemoveField(
            model_name='secpredtask',
            name='ambiguity',
        ),
        migrations.AddField(
            model_name='findpairstask',
            name='num_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='findpairstask',
            name='time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jftask',
            name='num_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jftask',
            name='time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='joinpairtask',
            name='find_pairs_task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='joinapp.FindPairsTask'),
        ),
        migrations.AddField(
            model_name='joinpairtask',
            name='num_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joinpairtask',
            name='time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pjftask',
            name='num_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pjftask',
            name='time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='secpredtask',
            name='num_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='secpredtask',
            name='time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='findpairstask',
            name='consensus',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskstats',
            name='selectivity',
            field=models.FloatField(default=0),
        ),
    ]
