# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0008_auto_20190607_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primaryitem',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='secondaryitem',
            name='item_id',
        ),
        migrations.AddField(
            model_name='primaryitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secondaryitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joinpairtask',
            name='find_pairs_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinapp.FindPairsTask'),
        ),
    ]
