# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-08 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0009_auto_20190607_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_2nd_list', models.BooleanField(default=False)),
                ('total_sample_size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_seen', models.IntegerField(default=0)),
                ('num_of_items', models.IntegerField(default=0)),
                ('estimator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinapp.Estimator')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='joinpairtask',
            name='consensus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='findpairstask',
            name='workers',
            field=models.ManyToManyField(related_name='find_pairs_task', to='joinapp.Worker'),
        ),
        migrations.AddField(
            model_name='jftask',
            name='workers',
            field=models.ManyToManyField(related_name='joinable_filter_task', to='joinapp.Worker'),
        ),
        migrations.AddField(
            model_name='joinpairtask',
            name='workers',
            field=models.ManyToManyField(related_name='join_pair_task', to='joinapp.Worker'),
        ),
        migrations.AddField(
            model_name='pjftask',
            name='workers',
            field=models.ManyToManyField(related_name='pre_join_task', to='joinapp.Worker'),
        ),
        migrations.AddField(
            model_name='secondaryitem',
            name='fstatistic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='joinapp.FStatistic'),
        ),
        migrations.AddField(
            model_name='secpredtask',
            name='workers',
            field=models.ManyToManyField(related_name='secondary_pred_task', to='joinapp.Worker'),
        ),
    ]
