# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-10 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0011_auto_20190607_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryitem',
            name='found_all_pairs',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
