# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-10 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0012_primaryitem_found_all_pairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryitem',
            name='matches_some',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='secpredtask',
            name='result',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
    ]
