# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-12 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0013_auto_20190610_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinpairtask',
            name='consensus',
        ),
        migrations.AlterField(
            model_name='joinpairtask',
            name='result',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
    ]
