# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0015_auto_20190614_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='findpairstask',
            old_name='time',
            new_name='average_time',
        ),
        migrations.RenameField(
            model_name='jftask',
            old_name='time',
            new_name='average_time',
        ),
        migrations.RenameField(
            model_name='joinpairtask',
            old_name='time',
            new_name='average_time',
        ),
        migrations.RenameField(
            model_name='pjftask',
            old_name='time',
            new_name='average_time',
        ),
        migrations.RenameField(
            model_name='secpredtask',
            old_name='time',
            new_name='average_time',
        ),
        migrations.AddField(
            model_name='findpairstask',
            name='total_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jftask',
            name='total_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='joinpairtask',
            name='total_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pjftask',
            name='total_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='secpredtask',
            name='total_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='joinpairtask',
            name='find_pairs_task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='joinapp.FindPairsTask'),
        ),
        migrations.AlterField(
            model_name='primaryitem',
            name='pjf',
            field=models.CharField(default='false', max_length=10),
        ),
        migrations.AlterField(
            model_name='secondaryitem',
            name='pjf',
            field=models.CharField(default='false', max_length=10),
        ),
    ]
