# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0016_auto_20190619_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryitem',
            name='num_prims_left',
            field=models.IntegerField(default=0),
        ),
    ]
