# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0017_secondaryitem_num_prims_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempjfpair',
            name='consensus',
        ),
        migrations.AddField(
            model_name='findpairstask',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itempjfpair',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itempjfpair',
            name='result',
            field=models.NullBooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='jftask',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='joinpairtask',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pjftask',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='primaryitem',
            name='has_all_join_pairs',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='secpredtask',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='findpairstask',
            name='consensus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pjftask',
            name='consensus',
            field=models.BooleanField(default=False),
        ),
    ]
