# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-26 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinapp', '0018_auto_20190621_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='findpairstask',
            name='secondary_item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='joinapp.SecondaryItem'),
        ),
        migrations.AddField(
            model_name='joinpairtask',
            name='has_same_pjf',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='secondaryitem',
            name='found_all_pairs',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
